# Generated by Django 4.2.9 on 2024-01-11 02:12

import crypto.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", crypto.models.TronAddressField(max_length=34, unique=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=0, default=0, max_digits=64),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChainTron",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(max_length=10)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("shasta", "Shasta"),
                            ("mainnet", "Mainnet"),
                            ("nile", "Nile"),
                            ("tronex", "Tronex"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "minimum_balance",
                    models.DecimalField(
                        decimal_places=0, default=30000000.0, max_digits=50
                    ),
                ),
                (
                    "refill_value",
                    models.DecimalField(
                        decimal_places=0, default=40000000.0, max_digits=50
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChainAdminAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("private_key", models.CharField(max_length=64)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chain_admin_addresses",
                        to="crypto.address",
                    ),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_addresses",
                        to="crypto.chaintron",
                    ),
                ),
            ],
            options={
                "unique_together": {("address", "chain")},
            },
        ),
        migrations.CreateModel(
            name="ChainAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_checked_block", models.PositiveBigIntegerField(default=0)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chain_addresses",
                        to="crypto.address",
                    ),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="crypto.chaintron",
                    ),
                ),
            ],
            options={
                "unique_together": {("address", "chain")},
            },
        ),
    ]
